language: python
python:
  - "3.5"
  - "3.4"
  - "3.3"
# command to install dependencies, e.g. pip install -r requirements.txt
install: "pip install -r requirements.txt"
# command to run tests, e.g. python setup.py test
script:  "python manage.py test"