# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-03 05:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('man', models.CharField(max_length=20)),
                ('substitute', models.CharField(blank=True, max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='TableOfMonth',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=20)),
                ('confirm', models.CharField(blank=True, max_length=20)),
                ('date', models.DateField()),
                ('notes', models.TextField(blank=True, default='')),
            ],
        ),
        migrations.AddField(
            model_name='shift',
            name='table',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shifts', to='tables_of_month.TableOfMonth'),
        ),
    ]
