# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-31 07:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kmID', models.CharField(blank=True, max_length=8)),
                ('edocID', models.CharField(blank=True, max_length=20)),
                ('emailID', models.CharField(blank=True, max_length=20)),
                ('name', models.CharField(max_length=20)),
                ('birthdate', models.DateField(blank=True)),
                ('personalID', models.CharField(blank=True, max_length=10)),
                ('location', models.CharField(blank=True, max_length=60)),
                ('location1', models.CharField(blank=True, editable=False, max_length=20)),
                ('location2', models.CharField(blank=True, editable=False, max_length=20)),
                ('location3', models.CharField(blank=True, editable=False, max_length=20)),
                ('title', models.CharField(max_length=20)),
                ('lastchangetime', models.DateTimeField(auto_now=True, verbose_name='上次修改時間')),
                ('notes', models.TextField(blank=True, default='')),
            ],
            options={
                'verbose_name': '人員',
            },
        ),
    ]
