# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-31 08:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_auto_20160331_1539'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='title',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
